# This message contains statistics from lsd_slam::DepthMap.
std_msgs/Header header

float32 msUpdate
float32 msCreate
float32 msFinalize
float32 msObserve
float32 msRegularize
float32 msPropagate
float32 msFillHoles
float32 msSetDepth
float32 nAvgUpdate
float32 nAvgCreate
float32 nAvgFinalize
float32 nAvgObserve
float32 nAvgRegularize
float32 nAvgPropagate
float32 nAvgFillHoles
float32 nAvgSetDepth